package entity;

/**
 * TDeviceSearch generated by MyEclipse Persistence Tools
 */

public class TDeviceSearch implements java.io.Serializable {

	// Fields

	private Integer idBlueprint;

	private String partName;

	private String deviceCode;

	private String snBlueprint;

	private String categoryString;

	private String blueprintName;

	private String deviceAliasName;

	// Constructors

	/** default constructor */
	public TDeviceSearch() {
	}

	/** minimal constructor */
	public TDeviceSearch(Integer idBlueprint) {
		this.idBlueprint = idBlueprint;
	}

	/** full constructor */
	public TDeviceSearch(Integer idBlueprint, String partName,
			String deviceCode, String snBlueprint, String categoryString,
			String blueprintName, String deviceAliasName) {
		this.idBlueprint = idBlueprint;
		this.partName = partName;
		this.deviceCode = deviceCode;
		this.snBlueprint = snBlueprint;
		this.categoryString = categoryString;
		this.blueprintName = blueprintName;
		this.deviceAliasName = deviceAliasName;
	}

	// Property accessors

	public Integer getIdBlueprint() {
		return this.idBlueprint;
	}

	public void setIdBlueprint(Integer idBlueprint) {
		this.idBlueprint = idBlueprint;
	}

	public String getPartName() {
		return this.partName;
	}

	public void setPartName(String partName) {
		this.partName = partName;
	}

	public String getDeviceCode() {
		return this.deviceCode;
	}

	public void setDeviceCode(String deviceCode) {
		this.deviceCode = deviceCode;
	}

	public String getSnBlueprint() {
		return this.snBlueprint;
	}

	public void setSnBlueprint(String snBlueprint) {
		this.snBlueprint = snBlueprint;
	}

	public String getCategoryString() {
		return this.categoryString;
	}

	public void setCategoryString(String categoryString) {
		this.categoryString = categoryString;
	}

	public String getBlueprintName() {
		return this.blueprintName;
	}

	public void setBlueprintName(String blueprintName) {
		this.blueprintName = blueprintName;
	}

	public String getDeviceAliasName() {
		return this.deviceAliasName;
	}

	public void setDeviceAliasName(String deviceAliasName) {
		this.deviceAliasName = deviceAliasName;
	}

}