package entity;

/**
 * TFixedCategory generated by MyEclipse Persistence Tools
 */

public class TFixedCategory implements java.io.Serializable {

	// Fields

	private Integer idCat;
	private String categoryLevel;
	private String categoryName;
	private String categoryNo;
	private Integer idUp;

	// Constructors

	/** default constructor */
	public TFixedCategory() {
	}

	/** full constructor */
	public TFixedCategory(String categoryLevel, String categoryName,
			String categoryNo, Integer idUp) {
		this.categoryLevel = categoryLevel;
		this.categoryName = categoryName;
		this.categoryNo = categoryNo;
		this.idUp = idUp;
	}

	// Property accessors

	public Integer getIdCat() {
		return this.idCat;
	}

	public void setIdCat(Integer idCat) {
		this.idCat = idCat;
	}

	public String getCategoryLevel() {
		return this.categoryLevel;
	}

	public void setCategoryLevel(String categoryLevel) {
		this.categoryLevel = categoryLevel;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getCategoryNo() {
		return this.categoryNo;
	}

	public void setCategoryNo(String categoryNo) {
		this.categoryNo = categoryNo;
	}

	public Integer getIdUp() {
		return this.idUp;
	}

	public void setIdUp(Integer idUp) {
		this.idUp = idUp;
	}

}