package entity;

/**
 * TJjbaseSearch generated by MyEclipse Persistence Tools
 */

public class TJjbaseSearch implements java.io.Serializable {

	// Fields

	private Integer idBlueprint;

	private String blueprintProject;

	private String projectName;

	private String categoryString;

	private String blueprintName;

	private String snBlueprint;

	// Constructors

	/** default constructor */
	public TJjbaseSearch() {
	}

	/** minimal constructor */
	public TJjbaseSearch(Integer idBlueprint) {
		this.idBlueprint = idBlueprint;
	}

	/** full constructor */
	public TJjbaseSearch(Integer idBlueprint, String blueprintProject,
			String projectName, String categoryString, String blueprintName,
			String snBlueprint) {
		this.idBlueprint = idBlueprint;
		this.blueprintProject = blueprintProject;
		this.projectName = projectName;
		this.categoryString = categoryString;
		this.blueprintName = blueprintName;
		this.snBlueprint = snBlueprint;
	}

	// Property accessors

	public Integer getIdBlueprint() {
		return this.idBlueprint;
	}

	public void setIdBlueprint(Integer idBlueprint) {
		this.idBlueprint = idBlueprint;
	}

	public String getBlueprintProject() {
		return this.blueprintProject;
	}

	public void setBlueprintProject(String blueprintProject) {
		this.blueprintProject = blueprintProject;
	}

	public String getProjectName() {
		return this.projectName;
	}

	public void setProjectName(String projectName) {
		this.projectName = projectName;
	}

	public String getCategoryString() {
		return this.categoryString;
	}

	public void setCategoryString(String categoryString) {
		this.categoryString = categoryString;
	}

	public String getBlueprintName() {
		return this.blueprintName;
	}

	public void setBlueprintName(String blueprintName) {
		this.blueprintName = blueprintName;
	}

	public String getSnBlueprint() {
		return this.snBlueprint;
	}

	public void setSnBlueprint(String snBlueprint) {
		this.snBlueprint = snBlueprint;
	}

}