package entity;

/**
 * TRolePopedom generated by MyEclipse Persistence Tools
 */

public class TRolePopedom implements java.io.Serializable {

	// Fields

	private TRolePopedomId id;

	// Constructors

	/** default constructor */
	public TRolePopedom() {
	}
        
        public TRolePopedom(String roleName,String popedomName){
            TRole trole=new TRole();
            trole.setRoleName(roleName);
            TPopedom tpopedom=new TPopedom();
            tpopedom.setPopedomName(popedomName);
            
            TRolePopedomId id=new TRolePopedomId();
            id.setTRole(trole);
            id.setTPopedom(tpopedom);
            setId(id);
        }

	/** full constructor */
	public TRolePopedom(TRolePopedomId id) {
		this.id = id;
	}

	// Property accessors

	public TRolePopedomId getId() {
		return this.id;
	}

	public void setId(TRolePopedomId id) {
		this.id = id;
	}

}