package entity;

/**
 * TRolePopedomId generated by MyEclipse Persistence Tools
 */

public class TRolePopedomId implements java.io.Serializable {

	// Fields

	private TRole TRole;

	private TPopedom TPopedom;

	// Constructors

	/** default constructor */
	public TRolePopedomId() {
	}

	/** full constructor */
	public TRolePopedomId(TRole TRole, TPopedom TPopedom) {
		this.TRole = TRole;
		this.TPopedom = TPopedom;
	}

	// Property accessors

	public TRole getTRole() {
		return this.TRole;
	}

	public void setTRole(TRole TRole) {
		this.TRole = TRole;
	}

	public TPopedom getTPopedom() {
		return this.TPopedom;
	}

	public void setTPopedom(TPopedom TPopedom) {
		this.TPopedom = TPopedom;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TRolePopedomId))
			return false;
		TRolePopedomId castOther = (TRolePopedomId) other;

		return ((this.getTRole() == castOther.getTRole()) || (this.getTRole() != null
				&& castOther.getTRole() != null && this.getTRole().equals(
				castOther.getTRole())))
				&& ((this.getTPopedom() == castOther.getTPopedom()) || (this
						.getTPopedom() != null
						&& castOther.getTPopedom() != null && this
						.getTPopedom().equals(castOther.getTPopedom())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTRole() == null ? 0 : this.getTRole().hashCode());
		result = 37 * result
				+ (getTPopedom() == null ? 0 : this.getTPopedom().hashCode());
		return result;
	}

}