package entity;

import java.util.HashSet;
import java.util.Set;

/**
 * TRole generated by MyEclipse Persistence Tools
 */

public class TRole implements java.io.Serializable {

	// Fields

	private String roleName;

	private String memo;

	private Set TUsers = new HashSet(0);

	private Set TRolePopedoms = new HashSet(0);

	// Constructors

	/** default constructor */
	public TRole() {
	}

	/** minimal constructor */
	public TRole(String roleName) {
		this.roleName = roleName;
	}

	/** full constructor */
	public TRole(String roleName, String memo, Set TUsers, Set TRolePopedoms) {
		this.roleName = roleName;
		this.memo = memo;
		this.TUsers = TUsers;
		this.TRolePopedoms = TRolePopedoms;
	}

	// Property accessors

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public Set getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set TUsers) {
		this.TUsers = TUsers;
	}

	public Set getTRolePopedoms() {
		return this.TRolePopedoms;
	}

	public void setTRolePopedoms(Set TRolePopedoms) {
		this.TRolePopedoms = TRolePopedoms;
	}

}