package entity;

/**
 * TUserCategoryId generated by MyEclipse Persistence Tools
 */

public class TUserCategoryId implements java.io.Serializable {

	// Fields

	private TUser TUser;

	private String categoryString;

	// Constructors

	/** default constructor */
	public TUserCategoryId() {
	}

	/** full constructor */
	public TUserCategoryId(TUser TUser, String categoryString) {
		this.TUser = TUser;
		this.categoryString = categoryString;
	}

	// Property accessors

	public TUser getTUser() {
		return this.TUser;
	}

	public void setTUser(TUser TUser) {
		this.TUser = TUser;
	}

	public String getCategoryString() {
		return this.categoryString;
	}

	public void setCategoryString(String categoryString) {
		this.categoryString = categoryString;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TUserCategoryId))
			return false;
		TUserCategoryId castOther = (TUserCategoryId) other;

		return ((this.getTUser() == castOther.getTUser()) || (this.getTUser() != null
				&& castOther.getTUser() != null && this.getTUser().equals(
				castOther.getTUser())))
				&& ((this.getCategoryString() == castOther.getCategoryString()) || (this
						.getCategoryString() != null
						&& castOther.getCategoryString() != null && this
						.getCategoryString().equals(
								castOther.getCategoryString())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getTUser() == null ? 0 : this.getTUser().hashCode());
		result = 37
				* result
				+ (getCategoryString() == null ? 0 : this.getCategoryString()
						.hashCode());
		return result;
	}

}